# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  solidtimberbenchtops.com.au:
    site_hosts:
      - lcl.solidtimberbenchtops.com.au
    local_path: ../solidtimberbenchtops.com.au # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: wp@solidtimberbenchtops.com.au
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
