# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  solidtimberbenchtops.com.au:
    site_hosts:
      - solidtimberbenchtops.com.au
      - atl.live1.chillidevelopment.com
    local_path: ../solidtimberbenchtops.com.au # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:ChilliCreative/solidtimberbenchtops.com.au.git # replace with your Git repo URL
    #repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: develop
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
